### ISSUE TITLE
Add CI using GitHub actions

### ISSUE THREAD

**Issue by SaadiSave** [mschweiger/orbiter#16]
This project could benefit from a continuous integration setup, so that any build errors are caught quickly. Since GitHub actions is free for public repositories, it is ideal for this project. I am willing to contribute a PR with the CI workflow if this issue is accepted.

**Comment by mschweiger** [comment]
There is already a PR #7 on that topic. Is that approximately what you had in mind, or is your suggestion different? I am interested in CI, but don't know the first thing on setting it up, so all help is appreciated.

**Comment by SaadiSave** [comment]
Yes, that is what I had in mind. The pull request looks good.
