### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by hughesjs** [mschweiger/orbiter#9]
Given how quickly development is likely to pick up on this project, might it be worth us getting a project Discord server up and running?

Happy to organise this but figured I'd ask first.

**Comment by thewonderidiot** [comment]
There's an [official Orbiter-Forum discord server](https://www.orbiter-forum.com/threads/the-official-discord-server-now-available.35624/), with a freshly made "Orbiter Development" section. :smiley:

**Comment by hughesjs** [comment]
Guess I'd best get making my 10 forum posts...

**Comment by supersonic71** [comment]
Would really appreciate if it wasn't linked to having 10 forum posts. 
It increases the barrier to entry.
